### ISSUE TITLE
能否添加关键字过滤功能

### ISSUE THREAD

**Issue by thomasgogo** [OneOaaS/graphtrees#1]
dear itnihao:
      试用了一下graphtrees,功能还是挺赞的.但还是想问下,能否添加关键字过滤功能,这样做虽然跟zatree功能重叠.但是不失为一个很赞的功能点.

**Comment by zhausong** [comment]
@doubinyang 您好，graphtrees不支持关键字过滤，将来也不做考虑。这个功能会在一个单独的模块提供，目前暂未开源。谢谢关注！
