### ISSUE TITLE
求3.0.4版本支持

### ISSUE THREAD

**Issue by overawe** [OneOaaS/graphtrees#11]
3.0.3 有个漏洞要修复， 全部开发都有graphtrees 。。。。。求支持

**Comment by meetbill** [comment]
https://github.com/BillWang139967/graphtrees

**Comment by meetbill** [comment]
可以下载下下面地址里zabbix.tar.gz 包，已经在3.0.4里面放了graphtrees，可以试试，或者可以等原作者出版本哦。https://github.com/BillWang139967/zabbix_install/tree/master/zabbix3.0.4/server

**Comment by h3llowor1d** [comment]
@overawe  @BillWang139967   3.0.4 新版

**Comment by meetbill** [comment]
好的，试试，有什么新的功能吗？我看目录结构变了

**Comment by meetbill** [comment]
@h3llowor1d 貌似有点问题

**Comment by h3llowor1d** [comment]
@BillWang139967 刚刚reset了一下 重新push了

**Comment by meetbill** [comment]
@h3llowor1d 
在web点击graphtree提示错误如下
Fatal error: Uncaught --> Smarty: unable to write file /data/web/zabbix/oneoaas/templates_c/wrt57ae4358487d24_04091103 <-- thrown in /data/web/zabbix/oneoaas/libs/sysplugins/smarty_internal_runtime_writefile.php on line 48

**Comment by h3llowor1d** [comment]
@BillWang139967 oneoaas/templates_c这个目录需要写的权限

**Comment by meetbill** [comment]
ok，可以了
