### ISSUE TITLE
对orcale 数据库是否支持

### ISSUE THREAD

**Issue by zhou-mfk** [OneOaaS/graphtrees#12]
你好，
今天安装使用了graphtrees 发现不能显示图形，错误提示如下：
SQL error [ORA-00911: invalid character] in [
SELECT DISTINCT
g.graphid,g.graphtype
FROM
items_applications ia,
`graphs_items` gi,
`graphs` g
WHERE ia.applicationid = 101978
AND gi.`itemid` = ia.`itemid`
AND g.`graphid` = gi.`graphid`
AND g.flags IN ('0', '4')
ORDER BY g.name]
oci_fetch_assoc(): ORA-24374: define not done before fetch or execute and fetch [graphtree.right.php:175 → DBfetch() → oci_fetch_assoc() in include/db.inc.php:598]

zabbix 3.0.3 
数据是使用的oracle 数据库

**Comment by zhou-mfk** [comment]
这个问题已解决，主要SQL语句的问题。oracle数据库所写的格式与代码中的SQL语句不一致导致。
还有一个问题，就是g.name排序问题，这个，在SELECT DISTINCT g.graphid,g.graphtype FROM ..... 如果没有g.name 需要把order by g.name 换成order by g.graphid

**Comment by h3llowor1d** [comment]
@zhou-mfk  是的 thx

**Comment by zhou-mfk** [comment]
@h3llowor1d  为什么绘图的图像显示的模糊，不是很清晰？ 单个大图是清晰的。

**Comment by h3llowor1d** [comment]
@zhou-mfk  因为要在一页展示更多的图像 压缩了图像的尺寸
