### ISSUE TITLE
web界面点击graphtree后，页面找不到

### ISSUE THREAD

**Issue by tigermysql** [OneOaaS/graphtrees#14]
系统：centos7
zabbix：3.0.4（rpm）
web：httpd
通过yum安装成功zabbix3.0.4后安装graphtree，在web界面显示有graphtree图标，但是点击后页面找不到，查看apache访问日志，错误返回码404，在安装graphtree过程中无报错

**Comment by zhausong** [comment]
进入你的zabbix web目录，执行以下命令

```
#tree oneoaas
或者是
#ls  oneoaas
```

**Comment by h3llowor1d** [comment]
@tigermysql 项目路径问题
