### ISSUE TITLE
web

### ISSUE THREAD

**Issue by tigermysql** [OneOaaS/graphtrees#15]

**Comment by tigermysql** [comment]
打开的web界面，不显示图片。图片为叉的状态

**Comment by zhausong** [comment]
@tigermysql Apache不支持http://x.x.x.x/zabbix/index.php 方式访问.需调整为http://x.x.x.x/index.php访问

**Comment by tigermysql** [comment]
现在是就http://x.x.x.x/oneoaas/graphtree.php?ddreset=1的访问方式，可以看到主机，也能看到application的几个分组，但是图示的话为叉

**Comment by h3llowor1d** [comment]
@tigermysql bug修复
