### ISSUE TITLE
使用oracle数据库时有语法问题

### ISSUE THREAD

**Issue by kakamylove** [OneOaaS/graphtrees#2]
后台使用oracle数据库，点击左侧列表报无效的字符，应该是调用SQL中表名外层用全角单引号，可以改成用半角双引号。

**Comment by zhausong** [comment]
@kakamylove 可以确定是这个问题吗，我这缺少Oracle环境没去验证，希望能够提交更多信息，谢谢

**Comment by kakamylove** [comment]
报错信息如下
SQL error [ORA-00911: invalid character] in [
SELECT DISTINCT

g.graphid,g.graphtype

FROM

`graphs` g,

`graphs_items` gi,

`items` i,

`hosts` h,

`hosts_groups` hg

WHERE i.hostid = h.`hostid`

AND gi.graphid = g.graphid

AND i.itemid = gi.itemid

AND g.flags IN ('0', '4')

AND hg.groupid = 12

AND hg.hostid = h.hostid

AND h.status = 0

AND EXISTS

(SELECT

NULL

FROM

`items` i

WHERE h.hostid = i.hostid

AND i.status = 0

AND i.flags IN (0, 4))

ORDER BY g.name ]

oci_fetch_assoc(): ORA-24374: define not done before fetch or execute and fetch [graphtree.right.php:125 → DBfetch() → oci_fetch_assoc() in include/db.inc.php:598]

**Comment by kakamylove** [comment]
您好，保存信息如下，网站上应该做了转换，邮件会更清楚一些。

```
SQL error [ORA-00911: invalid character] in [
SELECT DISTINCT
       g.graphid,g.graphtype
FROM
`graphs` g,
`graphs_items` gi,
`items` i,
`hosts` h,
`hosts_groups` hg
WHERE i.hostid = h.`hostid`
AND gi.graphid = g.graphid
AND i.itemid = gi.itemid
AND g.flags IN ('0', '4')
AND hg.groupid = 12
AND hg.hostid = h.hostid
AND h.status = 0
AND EXISTS
(SELECT
NULL
FROM
`items` i
WHERE h.hostid = i.hostid
AND i.status = 0
AND i.flags IN (0, 4))
ORDER BY g.name ]
oci_fetch_assoc(): ORA-24374: define not done before fetch or execute and fetch [graphtree.right.php:125 → DBfetch() → oci_fetch_assoc() in include/db.inc.php:598]
```

谢谢

**Comment by zhausong** [comment]
@kakamylove 可以加群Zabbix企业级分布式监控 271659981（验证码：Zabbix监控）方便远程debug。然后再返回这里记录，谢谢！

**Comment by kakamylove** [comment]
@itnihao 我是把graphtree.right.php文件中，SQL里面表名外的引号删掉解决了

**Comment by zhausong** [comment]
@kakamylove  稍后发布更新版本 谢谢

**Comment by zhausong** [comment]
@kakamylove 已更新 https://github.com/OneOaaS/graphtrees/commit/5d164bc066a59c122edeb8c2d5974fc05899041c
