### ISSUE TITLE
graphtrees图形报错显示不完整或者无数据

### ISSUE THREAD

**Issue by zc616427** [OneOaaS/graphtrees#3]
zabbix3.0平台使用3.0.1的web，数据库为mysql5.7，加入graphtrees是发现图形报错，报错代码如下
SELECT DISTINCT
g.graphid,g.graphtype
FROM
items_applications ia,
graphs_items gi,
graphs g
WHERE ia.applicationid = 346
AND gi.itemid = ia.itemid
AND g.graphid = gi.graphid
AND g.flags IN ('0', '4')
ORDER BY g.name
求指导

**Comment by zhausong** [comment]
已修复https://github.com/OneOaaS/graphtrees/commit/208f816ed71ea02a8b7cd47b1019251cb6e42a6d
