### ISSUE TITLE
zabbix3.0.0平台使用graphtrees报错

### ISSUE THREAD

**Issue by zc616427** [OneOaaS/graphtrees#6]
报错代码如下
Error in query [
SELECT DISTINCT
g.graphid,g.graphtype
FROM
`graphs` g,
`graphs_items` gi,
`items` i,
`hosts` h,
`hosts_groups` hg
WHERE i.hostid = h.`hostid`
AND gi.graphid = g.graphid
AND i.itemid = gi.itemid
AND g.flags IN ('0', '4')
AND hg.groupid = 29
AND hg.hostid = h.hostid
AND h.status = 0
AND EXISTS
(SELECT
NULL
FROM
`items` i
WHERE h.hostid = i.hostid
AND i.status = 0
AND i.flags IN (0, 4))
ORDER BY g.name ] [Expression #1 of ORDER BY clause is not in SELECT list, references column 'zabbix.g.name' which is not in SELECT list; this is incompatible with DISTINCT]

**Comment by h3llowor1d** [comment]
数据库版本不一样导致 开发时使用的数据库版本较低

**Comment by h3llowor1d** [comment]
@zc616427 你用的数据库是哪个版本的？

**Comment by zc616427** [comment]
@h3llowor1d 5.7

**Comment by h3llowor1d** [comment]
@zc616427 你先找到文件 去掉 order by 这部分sql，我们后续会使用多个版本数据库进行调试

**Comment by zc616427** [comment]
@h3llowor1d 期待早日完成，目前不影响

**Comment by h3llowor1d** [comment]
@zc616427 我们新上传了前端页面包，请您体验

**Comment by zc616427** [comment]
@h3llowor1d 是全部都需要更新么，还是只需要更新graphtree.right.php就可以了，报错代码存在于这个文件下

**Comment by h3llowor1d** [comment]
@zc616427  替换graphtree.right.php应该可以
