### ISSUE TITLE
Cant show pagingline

### ISSUE THREAD

**Issue by thuekx** [OneOaaS/graphtrees#7]
hi,

i have an error on zabbix 3.0.2 like this :
Argument 3 passed to getPagingLine() must be an instance of CUrl, none given, called in /usr/share/zabbix/graphtree.right.php on line 251 and defined [graphtree.right.php:251 → getPagingLine() in include/func.inc.php:1471]

anyone know the problem?

**Comment by zhausong** [comment]
@thuekx this is a bug,we will fix it soon

**Comment by zhausong** [comment]
@thuekx fix it ,code like this:

```
$url = new CUrl();
$pagingLine = getPagingLine($graph_list, ZBX_SORT_UP, $url);
```

you can fix the problem like this:

```
cd ${You PHP PATH}
mv graphtree.right.php graphtree.right.php-old
wget https://raw.githubusercontent.com/OneOaaS/graphtrees/master/web/graphtree.right.php
```

**Comment by thuekx** [comment]
Thank you very much

It's done
