### ISSUE TITLE
用到的 SQL 语法对 PostgreSQL 不兼容

### ISSUE THREAD

**Issue by wd** [OneOaaS/graphtrees#8]
mysql 里面可能支持表名或者字段上面加 ``，pg 不支持，会报错，修改代码去掉就好了。去掉这个之后，mysql 按说应该也是没问题的。patch 就不贴了，就是删除了`

我用 pg9.5 zabbix 3.0.3

**Comment by wd** [comment]
点了几下又发现新的问题。。

pg 里面 distinct 和 order by 一起用的时候，order by 的字段必须出现在 select 里面。

**Comment by h3llowor1d** [comment]
@wd 谢谢提出bug，会尽快解决的
